// <auto-generated />
using System;
using ClunyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClunyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductOptionGroups", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OptionGroupId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "OptionGroupId");

                    b.HasIndex("OptionGroupId");

                    b.ToTable("ProductOptionGroups", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 6,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 12,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            OptionGroupId = 1
                        },
                        new
                        {
                            ProductId = 15,
                            OptionGroupId = 1
                        });
                });

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pastries"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cold Beverages"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hot Beverages"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sandwiches"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pantry"
                        });
                });

            modelBuilder.Entity("Shared.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionGroupId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsDefault = true,
                            Name = "2% Milk",
                            OptionGroupId = 1,
                            PriceDelta = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsDefault = false,
                            Name = "Soy Milk",
                            OptionGroupId = 1,
                            PriceDelta = 0.75m
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsDefault = false,
                            Name = "Almond Milk",
                            OptionGroupId = 1,
                            PriceDelta = 0.75m
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsDefault = false,
                            Name = "Oat Milk",
                            OptionGroupId = 1,
                            PriceDelta = 0.75m
                        });
                });

            modelBuilder.Entity("Shared.Models.OptionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OptionGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsRequired = true,
                            Name = "Milk Options"
                        });
                });

            modelBuilder.Entity("Shared.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shared.Models.OrderSelectedOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderSelectedOptions");
                });

            modelBuilder.Entity("Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Classic French butter croissant baked fresh daily with flaky golden layers.",
                            IsAvailable = true,
                            Name = "Butter Croissant",
                            Price = 5.15m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Flaky croissant filled with premium dark chocolate batons.",
                            IsAvailable = true,
                            Name = "Chocolate Croissant",
                            Price = 5.75m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Croissant filled with almond cream, topped with toasted almonds and powdered sugar.",
                            IsAvailable = true,
                            Name = "Almond Croissant",
                            Price = 6.25m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Moist muffin packed with fresh blueberries and topped with crumble.",
                            IsAvailable = true,
                            Name = "Blueberry Muffin",
                            Price = 4.50m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Soft rolled pastry with cinnamon sugar filling and cream cheese icing.",
                            IsAvailable = true,
                            Name = "Cinnamon Roll",
                            Price = 5.95m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Espresso combined with chilled milk and served over ice.",
                            IsAvailable = true,
                            Name = "Iced Latte",
                            Price = 5.45m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Slow steeped coffee served cold for smooth and bold flavour.",
                            IsAvailable = true,
                            Name = "Cold Brew Coffee",
                            Price = 4.95m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Premium Japanese matcha whisked with milk and served over ice.",
                            IsAvailable = true,
                            Name = "Iced Matcha Latte",
                            Price = 6.25m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Freshly squeezed lemon juice with lightly sweetened chilled water.",
                            IsAvailable = true,
                            Name = "Fresh Lemonade",
                            Price = 4.75m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Spiced chai tea concentrate blended with cold milk and ice.",
                            IsAvailable = true,
                            Name = "Iced Chai Latte",
                            Price = 5.75m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Rich and concentrated espresso shot made from premium roasted beans.",
                            IsAvailable = true,
                            Name = "Espresso",
                            Price = 3.25m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Espresso diluted with hot water for a smooth coffee experience.",
                            IsAvailable = true,
                            Name = "Americano",
                            Price = 3.75m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Equal parts espresso, steamed milk, and silky foam.",
                            IsAvailable = true,
                            Name = "Cappuccino",
                            Price = 5.15m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Double espresso with velvety microfoam milk.",
                            IsAvailable = true,
                            Name = "Flat White",
                            Price = 5.45m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Steamed milk blended with rich melted chocolate and topped with foam.",
                            IsAvailable = true,
                            Name = "Hot Chocolate",
                            Price = 4.95m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Naturally fermented sourdough bread with crispy crust and airy crumb.",
                            IsAvailable = true,
                            Name = "Sourdough Loaf",
                            Price = 7.95m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Traditional French baguette with crunchy crust and soft interior.",
                            IsAvailable = true,
                            Name = "Baguette",
                            Price = 4.25m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Healthy whole wheat loaf baked fresh daily.",
                            IsAvailable = true,
                            Name = "Whole Wheat Bread",
                            Price = 6.75m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Hearty loaf made with mixed grains and seeds.",
                            IsAvailable = true,
                            Name = "Multigrain Bread",
                            Price = 7.25m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Description = "Roasted turkey breast, Swiss cheese, lettuce, and tomato on sourdough.",
                            IsAvailable = true,
                            Name = "Turkey & Swiss Sandwich",
                            Price = 9.95m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Description = "Grilled chicken breast with basil pesto, mozzarella, and arugula.",
                            IsAvailable = true,
                            Name = "Chicken Pesto Sandwich",
                            Price = 10.75m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Description = "Melted cheddar and mozzarella grilled on buttered artisan bread.",
                            IsAvailable = true,
                            Name = "Grilled Cheese Sandwich",
                            Price = 8.25m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "Roasted vegetables, hummus, spinach, and avocado on multigrain bread.",
                            IsAvailable = true,
                            Name = "Veggie Sandwich",
                            Price = 9.45m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Medium roast whole bean coffee with chocolate and caramel notes.",
                            IsAvailable = true,
                            Name = "House Coffee Beans (340g)",
                            Price = 16.95m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            Description = "Locally sourced raw wildflower honey.",
                            IsAvailable = true,
                            Name = "Artisan Honey Jar",
                            Price = 12.50m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Description = "Small batch strawberry jam made with fresh fruit.",
                            IsAvailable = true,
                            Name = "Strawberry Jam",
                            Price = 8.95m,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Description = "House-made granola with oats, nuts, seeds, and dried fruits.",
                            IsAvailable = true,
                            Name = "Granola Mix",
                            Price = 9.75m,
                            StockQuantity = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductOptionGroups", b =>
                {
                    b.HasOne("Shared.Models.OptionGroup", null)
                        .WithMany()
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductOptionGroups_OptionGroups_OptionGroupId");

                    b.HasOne("Shared.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductOptionGroups_Products_ProductId");
                });

            modelBuilder.Entity("Shared.Models.Option", b =>
                {
                    b.HasOne("Shared.Models.OptionGroup", "OptionGroup")
                        .WithMany("Options")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionGroup");
                });

            modelBuilder.Entity("Shared.Models.Order", b =>
                {
                    b.HasOne("Shared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.OrderSelectedOption", b =>
                {
                    b.HasOne("Shared.Models.Order", "Order")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shared.Models.Product", b =>
                {
                    b.HasOne("Shared.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shared.Models.OptionGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Shared.Models.Order", b =>
                {
                    b.Navigation("SelectedOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
